language: bash

cache:
  directories:
  - bats

services:
  - docker

install:
  - test -d bats || git clone --depth=1 --branch v0.4.0 https://github.com/sstephenson/bats.git
  - export PATH=./bats/bin:$PATH

script:
  - make test

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    make build;
    docker login -u="existenz" -p="$DOCKER_PASSWORD";
    docker push existenz/merge-back;
    fi
